source "https://rubygems.org"

gem "rack", "~> 2.2"
gem "puma", "~> 5.2"
gem "hanami-router", "~> 1.3"
gem "hanami-controller", "~> 1.3"
gem "ksuid", "~> 0.2.0"
gem "activerecord", "~> 6.1"
gem "pg", "~> 1.2"
